version: '2'
services:
  app:
    build: .
    command: terraform plan
    volumes:
      - .:/code
      - /root/creds/perfmatters/credentials:/root/.aws/credentials
      - /root/creds/perfmatters/terraform.tfstate:/code/terraform.tfstate
      - /root/creds/perfmatters/terraform.tfvars:/code/terraform.tfvars
