version: '2'
services:
  app:
    build: .
    command: terraform plan -state=/root/terraform/terraform.tfstate -var-file=/root/terraform/terraform.tfvars
    volumes:
      - .:/code
      - /root/creds/perfmatters/credentials:/root/.aws/credentials
      - /root/creds/perfmatters/terraform:/root/terraform
